### PR TITLE
Find duplicate files by comparing hashes of files

### PR DESCRIPTION
**Pull request by sudesh1611**

### CODE REVIEW

**Comment by sudesh1611** [comment]
Also please add hacktoberfest-accepted tag to the PR

**Review by sonuishaq67 — CHANGES_REQUESTED** [review]
Hey @sudesh1611 the script looks good 
can you make a small readme in your directory
and change the name of the directory

**Comment by sonuishaq67** [comment]
> Also please add hacktoberfest-accepted tag to the PR

sure will do that

**Comment by sudesh1611** [comment]
> 
> 
> Hey @sudesh1611 the script looks good
> can you make a small readme in your directory
> and change the name of the directory

Okay sure. What name do you want of directory?

**Comment by sonuishaq67** [comment]
something which describes your code functionality

**Comment by sudesh1611** [comment]
Added the required changes

**Review by sonuishaq67 — APPROVED** [review]

**Comment by sonuishaq67** [comment]
nice thanks for the contribution @sudesh1611 !

**Pull request merged**
