### PR TITLE
autocmt script with python

### PR DESCRIPTION
**Pull request by ghost**
i think this is helpful in some way.

### CODE REVIEW

**Review by sonuishaq67 — CHANGES_REQUESTED** [review]
hi @thettunaung228  can you make a small readme for this

**Comment by ghost** [comment]
@sonuishaq67 will this ok?i am beginner too

**Review by ghost — CHANGES_REQUESTED** [review]
can you please edit your readme heres some examples on how to do that
https://en.wikipedia.org/wiki/Markdown#Example

**Comment by ghost** [comment]
sry i cant still well-used github :p i hope this one can work. @cw0x413

**Review by sonuishaq67 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by sonuishaq67** [comment]
> sry i cant still well-used github :p i hope this one can work

Its okay thats what hacktober fest is for 
learning

**Pull request merged**
