### PR TITLE
ram-cache clear updated

### PR DESCRIPTION
**Pull request by prasannassp**
issue #14

### CODE REVIEW

**Comment by sonuishaq67** [comment]
HI @prasannassp looks like you deleted the readme for the project by mistake could you add it again?

**Comment by prasannassp** [comment]
It's added. Sorry for that.

**Review by sonuishaq67 — COMMENTED** [review]
Also is the sleep 30 very much required? or can it be lowered

**Comment by prasannassp** [comment]
Yes. For the safer side, we have to wait for approximately 30secs in order to give execution time for the swapoff command.

**Comment by sonuishaq67** [comment]
Okays thanks for the contribution!

**Comment by prasannassp** [comment]
Thank you @sonuishaq67

**Pull request merged**
